/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardScholarshipsRouteImport } from './routes/dashboard.scholarships'
import { Route as DashboardRoadmapsRouteImport } from './routes/dashboard.roadmaps'
import { Route as DashboardRewardsRouteImport } from './routes/dashboard.rewards'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardMentorRouteImport } from './routes/dashboard.mentor'
import { Route as DashboardLearningRouteImport } from './routes/dashboard.learning'
import { Route as DashboardInterviewsRouteImport } from './routes/dashboard.interviews'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard.finance'
import { Route as DashboardAssessmentRouteImport } from './routes/dashboard.assessment'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScholarshipsRoute = DashboardScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapsRoute = DashboardRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRewardsRoute = DashboardRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLearningRoute = DashboardLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssessmentRoute = DashboardAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assessment': typeof DashboardAssessmentRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/learning': typeof DashboardLearningRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/scholarships': typeof DashboardScholarshipsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assessment': typeof DashboardAssessmentRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/learning': typeof DashboardLearningRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/scholarships': typeof DashboardScholarshipsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/assessment': typeof DashboardAssessmentRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/learning': typeof DashboardLearningRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/scholarships': typeof DashboardScholarshipsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/assessment'
    | '/dashboard/finance'
    | '/dashboard/interviews'
    | '/dashboard/learning'
    | '/dashboard/mentor'
    | '/dashboard/resume'
    | '/dashboard/rewards'
    | '/dashboard/roadmaps'
    | '/dashboard/scholarships'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/assessment'
    | '/dashboard/finance'
    | '/dashboard/interviews'
    | '/dashboard/learning'
    | '/dashboard/mentor'
    | '/dashboard/resume'
    | '/dashboard/rewards'
    | '/dashboard/roadmaps'
    | '/dashboard/scholarships'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/assessment'
    | '/dashboard/finance'
    | '/dashboard/interviews'
    | '/dashboard/learning'
    | '/dashboard/mentor'
    | '/dashboard/resume'
    | '/dashboard/rewards'
    | '/dashboard/roadmaps'
    | '/dashboard/scholarships'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scholarships': {
      id: '/dashboard/scholarships'
      path: '/scholarships'
      fullPath: '/dashboard/scholarships'
      preLoaderRoute: typeof DashboardScholarshipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmaps': {
      id: '/dashboard/roadmaps'
      path: '/roadmaps'
      fullPath: '/dashboard/roadmaps'
      preLoaderRoute: typeof DashboardRoadmapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rewards': {
      id: '/dashboard/rewards'
      path: '/rewards'
      fullPath: '/dashboard/rewards'
      preLoaderRoute: typeof DashboardRewardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/learning': {
      id: '/dashboard/learning'
      path: '/learning'
      fullPath: '/dashboard/learning'
      preLoaderRoute: typeof DashboardLearningRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assessment': {
      id: '/dashboard/assessment'
      path: '/assessment'
      fullPath: '/dashboard/assessment'
      preLoaderRoute: typeof DashboardAssessmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAssessmentRoute: typeof DashboardAssessmentRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardInterviewsRoute: typeof DashboardInterviewsRoute
  DashboardLearningRoute: typeof DashboardLearningRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardRewardsRoute: typeof DashboardRewardsRoute
  DashboardRoadmapsRoute: typeof DashboardRoadmapsRoute
  DashboardScholarshipsRoute: typeof DashboardScholarshipsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAssessmentRoute: DashboardAssessmentRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardInterviewsRoute: DashboardInterviewsRoute,
  DashboardLearningRoute: DashboardLearningRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardRewardsRoute: DashboardRewardsRoute,
  DashboardRoadmapsRoute: DashboardRoadmapsRoute,
  DashboardScholarshipsRoute: DashboardScholarshipsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
